name: ✏️ 블로그 작성자 정보 수정
description: 기존 작성자 정보를 수정하고 싶으신가요?
title: "[작성자 수정] "
labels: ["author-update"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## ✏️ Hugging Face KREW 블로그 작성자 정보 수정
        
        기존에 등록된 작성자 정보를 수정할 수 있습니다.
        수정하고 싶은 필드만 입력하시면 됩니다. ✨

  - type: input
    id: author_key
    attributes:
      label: "수정할 작성자 ID"
      description: "기존에 등록된 작성자 ID를 입력해주세요."
      placeholder: "minju"
    validations:
      required: true

  - type: input
    id: name
    attributes:
      label: "실명 (수정 시에만 입력)"
      description: "실명을 수정하려면 입력해주세요."
      placeholder: "Song Chaewon"
    validations:
      required: false

  - type: input
    id: display_name
    attributes:
      label: "표시 이름 (수정 시에만 입력)"
      description: "블로그 표시명을 수정하려면 입력해주세요."
      placeholder: "Chaewon"
    validations:
      required: false

  - type: input
    id: email
    attributes:
      label: "이메일 주소 (수정 시에만 입력)"
      description: "이메일을 수정하려면 입력해주세요."
      placeholder: "chaewon@example.com"
    validations:
      required: false

  - type: input
    id: web
    attributes:
      label: "개인 웹사이트 또는 GitHub (수정 시에만 입력)"
      description: "웹사이트를 수정하려면 입력해주세요."
      placeholder: "https://github.com/username"
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: "자기소개 (수정 시에만 입력)"
      description: "자기소개를 수정하려면 입력해주세요."
      placeholder: "안녕하세요! AI/ML에 관심이 많은 개발자입니다. 🤗"
    validations:
      required: false

  - type: dropdown
    id: avatar_option
    attributes:
      label: "프로필 이미지 수정 여부"
      description: "프로필 이미지를 수정하시겠어요?"
      options:
        - "수정하지 않음"
        - "본인 GitHub 프로필 이미지로 변경"
        - "직접 업로드로 변경 (아래에 이미지 첨부)"
        - "기본 이미지로 변경"
    validations:
      required: true

  - type: textarea
    id: profile_image_upload
    attributes:
      label: "📸 프로필 이미지 첨부 (직접 업로드 변경 선택 시)"
      description: |
        **"직접 업로드로 변경"을 선택하신 경우**, 이 영역에 이미지를 첨부해주세요.
        
        **첨부 방법**: 
        - 파일을 이 텍스트 영역으로 **드래그 앤 드롭**
        - 클립보드에서 **Ctrl+V** (Mac: Cmd+V)로 붙여넣기
        
        **지원 형식**: PNG, JPG, JPEG, GIF, WebP (권장 크기: 200x200px)
      placeholder: |
        이미지를 여기에 드래그하거나 붙여넣기 해주세요...
        
        예시:
        ![프로필이미지](이미지URL)
    validations:
      required: false
