name: 📝 블로그 작성자 등록 신청
description: Hugging Face KREW 블로그에 글을 작성하고 싶으신가요? 작성자로 등록해보세요!
title: "[작성자 등록] "
labels: ["author-registration"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        ## 🤗 Hugging Face KREW 블로그 작성자 등록
        
        안녕하세요! Hugging Face KREW 블로그에 관심을 가져주셔서 감사합니다.
        
        아래 정보를 정확히 입력해주시면, 자동으로 PR이 생성되어 작성자로 등록됩니다.
        사진 업로드를 제외한 모든 필드는 필수입니다. ✨

  - type: input
    id: author_key
    attributes:
      label: "작성자 ID (영문)"
      description: "블로그에서 사용할 고유 ID를 영문으로 입력해주세요. (예: gildong)"
      placeholder: "gildong"
    validations:
      required: true

  - type: input
    id: name
    attributes:
      label: "실명"
      description: "실명을 영어로 입력해주세요. (예: Hong Gildong)"
      placeholder: "Hong Gildong"
    validations:
      required: true

  - type: input
    id: display_name
    attributes:
      label: "표시 이름"
      description: "블로그에 표시될 이름을 입력해주세요."
      placeholder: "Huggy"
    validations:
      required: true

  - type: input
    id: email
    attributes:
      label: "이메일 주소"
      description: "연락 가능한 이메일 주소를 입력해주세요."
      placeholder: "gildong@example.com"
    validations:
      required: true

  - type: input
    id: web
    attributes:
      label: "개인 웹사이트 또는 GitHub"
      description: "개인 웹사이트, GitHub 프로필, LinkedIn등의 URL을 입력해주세요."
      placeholder: "https://github.com/username"
    validations:
      required: true

  - type: input
    id: description
    attributes:
      label: "자기소개"
      description: "간단한 한 줄 자기소개를 작성해주세요. 블로그에 표시됩니다."
      placeholder: "안녕하세요! AI/ML에 관심이 많은 개발자입니다. 🤗"
    validations:
      required: true

  - type: dropdown
    id: avatar_option
    attributes:
      label: "프로필 이미지 옵션"
      description: "프로필 이미지를 어떻게 설정하시겠어요?"
      options:
        - "본인 GitHub 프로필 이미지 사용"
        - "직접 업로드 (아래에 이미지 첨부)"
        - "기본 이미지 사용"
    validations:
      required: true

  - type: textarea
    id: profile_image_upload
    attributes:
      label: "📸 프로필 이미지 첨부 (직접 업로드 선택 시)"
      description: |
        **"직접 업로드"를 선택하신 경우**, 이 영역에 이미지를 첨부해주세요.

        **지원 형식**: PNG, JPG, JPEG, GIF, WebP (권장 크기: 200x200px)
      placeholder: |
        이미지를 여기에 드래그하거나 붙여넣기 해주세요...
        
        예시:
        ![프로필이미지](이미지URL)
    validations:
      required: false

  - type: markdown
    attributes:
      value: |
        ---
        
        ### 🔄 다음 단계
        1. **이슈 제출** 후 자동으로 PR이 생성됩니다
        2. **관리자 검토** 후 PR이 승인되면 작성자로 등록됩니다
        3. **등록 완료** 후 블로그 글 작성을 시작할 수 있습니다
        
        궁금한 점이 있으시면 이 이슈에 댓글로 문의해주세요! 🤗