name: PR Preview

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.x
          bundler-cache: true

      - name: Install dependencies
        run: bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to Preview Branch
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git clone --branch gh-pages https://github.com/${{ github.repository }} preview
          mkdir -p preview/pull/${{ github.event.number }}
          cp -r _site/* preview/pull/${{ github.event.number }}/
          cd preview
          git add .
          git commit -m "Deploy PR #${{ github.event.number }} preview"
          git push origin gh-pages

      - name: Comment PR with Preview URL
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.MY_GITHUB_TOKEN }}
          script: |
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 PR Preview: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/pull/${{ github.event.number }}`
            })
